version: 2.1
# this is to mention the version of circle ci 
jobs:
 install:
  docker:
   - image: cimg/node:20.1.0
  working_directory: ~/repo 
  steps:
   - checkout
   - run: npm install
   - run: cd /home/circleci/repo
   - run: ls /home/circleci/repo/public
   - run: npm start
workflows:
 install_now:
  jobs:
   - install
