version: 2.1
# this is to mention the version of circle ci 
jobs:
 install:
  docker:
   - image: cimg/node:20.1.0
  steps:
   - checkout
   - run: npm install
   - run: pwd
   - run: npm start
workflows:
 install_now:
  jobs:
   - install
